[[graph.nodes]]
index = 0
value = 0
adj_list = [false, true, false, false, false, false, false, false, false, false]
edge_matrix = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

[[graph.nodes]]
index = 1
value = 0
adj_list = [false, false, true, true, false, false, false, false, false, false]
edge_matrix = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

[[graph.nodes]]
index = 2
value = 0
adj_list = [false, false, false, false, false, false, false, false, false, false]
edge_matrix = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

[[graph.nodes]]
index = 3
value = 0
adj_list = [false, false, false, false, false, false, false, false, false, false]
edge_matrix = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

[[graph.nodes]]
index = 4
value = 0
adj_list = [false, false, false, false, false, false, false, false, false, false]
edge_matrix = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

[[graph.nodes]]
index = 5
value = 0
adj_list = [false, false, false, false, false, false, false, false, false, false]
edge_matrix = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

[[graph.nodes]]
index = 6
value = 0
adj_list = [false, false, false, false, false, false, false, false, false, false]
edge_matrix = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

[[graph.nodes]]
index = 7
value = 0
adj_list = [false, false, false, false, false, false, false, false, false, false]
edge_matrix = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

[[graph.nodes]]
index = 8
value = 0
adj_list = [false, false, false, false, false, false, false, false, false, false]
edge_matrix = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

[[graph.nodes]]
index = 9
value = 0
adj_list = [false, false, false, false, false, false, false, false, false, false]
edge_matrix = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

[u]
index = 0
value = 0
adj_list = [false, false, false, false, false, false, false, false, false, false]
edge_matrix = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]